import "./globals.css";
import { Figtree } from "next/font/google";

export const figtree = Figtree({
  weight: ["400", "500", "700"], // or other weights you need
  subsets: ["latin"],
  variable: "--font-figtree",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${figtree.className} antialiased`}>{children}</body>
    </html>
  );
}
